# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Documentation

on: 
  push:
    branches:
      - main

jobs:
  build:

    runs-on: macos-latest-xlarge

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - uses: swift-actions/setup-swift@v1
      - name: Get swift version
        run: swift --version 
      - uses: actions/checkout@v3
      - name: Fix Up Private GitHub URLs
        # Add personal access token to all private repo URLs 
        run: find . -type f \( -name 'Package.swift' -o -name 'Package.resolved' \) -exec sed -i '' "s/https:\/\/github.com\/eu-digital-identity-wallet/https:\/\/${{ secrets.USER_NAME }}:${{ secrets.USER_GITHUB_TOKEN }}@github.com\/eu-digital-identity-wallet/g" {} \;
      - name: Generate Docs
        uses: fwcd/swift-docc-action@v1
        with:
          target: EudiWalletKit
          output: ./docs
          transform-for-static-hosting: 'true'
          disable-indexing: 'true'
          hosting-base-path: eudi-lib-ios-wallet-kit
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs
